/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BiosFileRouteImport } from './routes/$biosFile'
import { Route as AssetsSplatRouteImport } from './routes/assets/$'
import { Route as FontsSplatRouteImport } from './routes/fonts/$'
import { Route as ApiAuthGoogleRouteImport } from './routes/api/auth/google'
import { Route as ApiAuthLogoutRouteImport } from './routes/api/auth/logout'
import { Route as ApiAuthMeRouteImport } from './routes/api/auth/me'
import { Route as ApiSavesIndexRouteImport } from './routes/api/saves/index'
import { Route as ApiAuthGoogleCallbackRouteImport } from './routes/api/auth/google/callback'
import { Route as ApiRomIdNameRouteImport } from './routes/api/rom/$id/$name'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BiosFileRoute = BiosFileRouteImport.update({
  id: '/$biosFile',
  path: '/$biosFile',
  getParentRoute: () => rootRouteImport,
} as any)
const AssetsSplatRoute = AssetsSplatRouteImport.update({
  id: '/assets/$',
  path: '/assets/$',
  getParentRoute: () => rootRouteImport,
} as any)
const FontsSplatRoute = FontsSplatRouteImport.update({
  id: '/fonts/$',
  path: '/fonts/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthGoogleRoute = ApiAuthGoogleRouteImport.update({
  id: '/api/auth/google',
  path: '/api/auth/google',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthLogoutRoute = ApiAuthLogoutRouteImport.update({
  id: '/api/auth/logout',
  path: '/api/auth/logout',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthMeRoute = ApiAuthMeRouteImport.update({
  id: '/api/auth/me',
  path: '/api/auth/me',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSavesIndexRoute = ApiSavesIndexRouteImport.update({
  id: '/api/saves/',
  path: '/api/saves/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthGoogleCallbackRoute = ApiAuthGoogleCallbackRouteImport.update({
  id: '/callback',
  path: '/callback',
  getParentRoute: () => ApiAuthGoogleRoute,
} as any)
const ApiRomIdNameRoute = ApiRomIdNameRouteImport.update({
  id: '/api/rom/$id/$name',
  path: '/api/rom/$id/$name',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$biosFile': typeof BiosFileRoute
  '/assets/$': typeof AssetsSplatRoute
  '/fonts/$': typeof FontsSplatRoute
  '/api/auth/google': typeof ApiAuthGoogleRouteWithChildren
  '/api/auth/logout': typeof ApiAuthLogoutRoute
  '/api/auth/me': typeof ApiAuthMeRoute
  '/api/saves/': typeof ApiSavesIndexRoute
  '/api/auth/google/callback': typeof ApiAuthGoogleCallbackRoute
  '/api/rom/$id/$name': typeof ApiRomIdNameRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$biosFile': typeof BiosFileRoute
  '/assets/$': typeof AssetsSplatRoute
  '/fonts/$': typeof FontsSplatRoute
  '/api/auth/google': typeof ApiAuthGoogleRouteWithChildren
  '/api/auth/logout': typeof ApiAuthLogoutRoute
  '/api/auth/me': typeof ApiAuthMeRoute
  '/api/saves': typeof ApiSavesIndexRoute
  '/api/auth/google/callback': typeof ApiAuthGoogleCallbackRoute
  '/api/rom/$id/$name': typeof ApiRomIdNameRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$biosFile': typeof BiosFileRoute
  '/assets/$': typeof AssetsSplatRoute
  '/fonts/$': typeof FontsSplatRoute
  '/api/auth/google': typeof ApiAuthGoogleRouteWithChildren
  '/api/auth/logout': typeof ApiAuthLogoutRoute
  '/api/auth/me': typeof ApiAuthMeRoute
  '/api/saves/': typeof ApiSavesIndexRoute
  '/api/auth/google/callback': typeof ApiAuthGoogleCallbackRoute
  '/api/rom/$id/$name': typeof ApiRomIdNameRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$biosFile'
    | '/assets/$'
    | '/fonts/$'
    | '/api/auth/google'
    | '/api/auth/logout'
    | '/api/auth/me'
    | '/api/saves/'
    | '/api/auth/google/callback'
    | '/api/rom/$id/$name'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$biosFile'
    | '/assets/$'
    | '/fonts/$'
    | '/api/auth/google'
    | '/api/auth/logout'
    | '/api/auth/me'
    | '/api/saves'
    | '/api/auth/google/callback'
    | '/api/rom/$id/$name'
  id:
    | '__root__'
    | '/'
    | '/$biosFile'
    | '/assets/$'
    | '/fonts/$'
    | '/api/auth/google'
    | '/api/auth/logout'
    | '/api/auth/me'
    | '/api/saves/'
    | '/api/auth/google/callback'
    | '/api/rom/$id/$name'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BiosFileRoute: typeof BiosFileRoute
  AssetsSplatRoute: typeof AssetsSplatRoute
  FontsSplatRoute: typeof FontsSplatRoute
  ApiAuthGoogleRoute: typeof ApiAuthGoogleRouteWithChildren
  ApiAuthLogoutRoute: typeof ApiAuthLogoutRoute
  ApiAuthMeRoute: typeof ApiAuthMeRoute
  ApiSavesIndexRoute: typeof ApiSavesIndexRoute
  ApiRomIdNameRoute: typeof ApiRomIdNameRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$biosFile': {
      id: '/$biosFile'
      path: '/$biosFile'
      fullPath: '/$biosFile'
      preLoaderRoute: typeof BiosFileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assets/$': {
      id: '/assets/$'
      path: '/assets/$'
      fullPath: '/assets/$'
      preLoaderRoute: typeof AssetsSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fonts/$': {
      id: '/fonts/$'
      path: '/fonts/$'
      fullPath: '/fonts/$'
      preLoaderRoute: typeof FontsSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/google': {
      id: '/api/auth/google'
      path: '/api/auth/google'
      fullPath: '/api/auth/google'
      preLoaderRoute: typeof ApiAuthGoogleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/logout': {
      id: '/api/auth/logout'
      path: '/api/auth/logout'
      fullPath: '/api/auth/logout'
      preLoaderRoute: typeof ApiAuthLogoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/me': {
      id: '/api/auth/me'
      path: '/api/auth/me'
      fullPath: '/api/auth/me'
      preLoaderRoute: typeof ApiAuthMeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/saves/': {
      id: '/api/saves/'
      path: '/api/saves'
      fullPath: '/api/saves/'
      preLoaderRoute: typeof ApiSavesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/google/callback': {
      id: '/api/auth/google/callback'
      path: '/callback'
      fullPath: '/api/auth/google/callback'
      preLoaderRoute: typeof ApiAuthGoogleCallbackRouteImport
      parentRoute: typeof ApiAuthGoogleRoute
    }
    '/api/rom/$id/$name': {
      id: '/api/rom/$id/$name'
      path: '/api/rom/$id/$name'
      fullPath: '/api/rom/$id/$name'
      preLoaderRoute: typeof ApiRomIdNameRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface ApiAuthGoogleRouteChildren {
  ApiAuthGoogleCallbackRoute: typeof ApiAuthGoogleCallbackRoute
}

const ApiAuthGoogleRouteChildren: ApiAuthGoogleRouteChildren = {
  ApiAuthGoogleCallbackRoute: ApiAuthGoogleCallbackRoute,
}

const ApiAuthGoogleRouteWithChildren = ApiAuthGoogleRoute._addFileChildren(
  ApiAuthGoogleRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BiosFileRoute: BiosFileRoute,
  AssetsSplatRoute: AssetsSplatRoute,
  FontsSplatRoute: FontsSplatRoute,
  ApiAuthGoogleRoute: ApiAuthGoogleRouteWithChildren,
  ApiAuthLogoutRoute: ApiAuthLogoutRoute,
  ApiAuthMeRoute: ApiAuthMeRoute,
  ApiSavesIndexRoute: ApiSavesIndexRoute,
  ApiRomIdNameRoute: ApiRomIdNameRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
